### PR TITLE
Replace obsolete markdown renderer and support syntax highlighting

### LINKED ISSUE #19: Newlines in code blocks do not get formatted properly
When I type:

``````
```java
public class Test
{
    public static void main(String[] args)
    {
        System.out.println("Hi.");
    }
}
```
``````

I expect every line of code to be on its own line - instead, all lines get condensed onto one line:

screenshot

### PR DESCRIPTION
**Pull request by adalinesimonian**
Fixes #19, #16

Changes:

- Update project to Visual Studio 2017
- Target .NET Framework 4.7
- Use Markdig as Markdown renderer
- Support syntax highlighting
- Support CommonMark extensions
- Bump extension version to 1.1.0

### CODE REVIEW

**Comment by sebinsua** [comment]
Awesome! :D

**Comment by hisplan** [comment]
Would be really nice if someone can create an installation package and release this.

**Comment by zenglian** [comment]
@vsimonian Could you please share the msi somewhere (e.g., your github)?

**Comment by zenglian** [comment]
Below is my build, but the look and feel is not as my expection.

[MarkdownOutlookSetup.zip](https://github.com/mmanela/MarkdownOutlook/files/2402032/MarkdownOutlookSetup.zip)

**Pull request merged**
